### ISSUE TITLE
gV bad output

### ISSUE THREAD

**Issue by VadimSam** [VadimSam/LR3_Git#1]
# Brief intro
While calling from  aeV this method works perfectly fine, but calling it outside causes bad printing.
"Bad printing" consists in  incomplete printing of all parameters of vehicle.
# How to reproduce
To reproduce,  try to call gV from main  menu, and than gaze on obviously incomplete terminal output.

Related [COMMIT]( https://github.com/VadimSam/LR3_Git/commit/bfc7dacb5c50580471e67431d59195a1a1d1faac)

**Comment by VadimSam** [comment]
Let's discuss this problem now. @IvanTitan0ff

**Comment by IvanTitan0ff** [comment]
ok

**Comment by VadimSam** [comment]
Any ideas on  this behavior?

**Comment by IvanTitan0ff** [comment]
Maybe we should use the same function of output as in adding or editing cars?

**Comment by VadimSam** [comment]
No,  decomposition will be broken then.

**Comment by IvanTitan0ff** [comment]
maybe "go to"?

**Comment by VadimSam** [comment]
Whoops. My bad. I misread your message. But as for  function, it is already here in Auxiliary methods section in "MainWrapper.h" called pV.

**Comment by IvanTitan0ff** [comment]
Let's use discord to discuss it

**Comment by VadimSam** [comment]
Forget about goto operator! You don't want to incur the righteous wrath of Uncle Dijkstra, do you?

**Comment by IvanTitan0ff** [comment]
if it's possible

**Comment by VadimSam** [comment]
ASAP

**Comment by IvanTitan0ff** [comment]
I'm in

**Comment by VadimSam** [comment]
As for goto. https://homepages.cwi.nl/~storm/teaching/reader/Dijkstra68.pdf

**Comment by VadimSam** [comment]
@IvanTitan0ff, anything new?

**Comment by VadimSam** [comment]
I suppose that problem located somewhere in fV. Agree?

**Comment by VadimSam** [comment]
@IvanTitan0ff Please ask on StackOverflow. Cause I am lacking of any ideas.

**Comment by IvanTitan0ff** [comment]
" VIN: 1
Door 0 is 1
Window 0 is 1 for 1
Pedal 0 is 0 for 1
Light 0 is 1
Steering wheel is turned for 1
Speed 0 is 1 and is set om this speed 1"
Is it normal that 1st number of all car's parts is 0?

**Comment by VadimSam** [comment]
Scrsht pls

**Comment by VadimSam** [comment]
As for "Is it normal that 1st number of all car's parts is 0?" - I suppose no.

**Comment by VadimSam** [comment]
Share a bit more info please. Not just output in  term.

**Comment by IvanTitan0ff** [comment]
![2021-11-14 (2)](https://user-images.githubusercontent.com/93482422/141674170-d5fa1d10-2de7-4507-b7d9-def803b76644.png)

**Comment by IvanTitan0ff** [comment]
![2021-11-14 (1)](https://user-images.githubusercontent.com/93482422/141674203-5337b2c2-e7d6-42c2-843b-912706b44736.png)

**Comment by VadimSam** [comment]
Please concentrate on the issue

**Comment by VadimSam** [comment]
Awkward silence... UpDaTeS @IvanTitan0ff?

**Comment by IvanTitan0ff** [comment]
Already sent on stackoverflow

**Comment by VadimSam** [comment]
Provide URL, please.

**Comment by IvanTitan0ff** [comment]
https://ru.stackoverflow.com/questions/1349606/%d0%9e%d1%88%d0%b8%d0%b1%d0%ba%d0%b0-%d0%bf%d1%80%d0%b8-%d0%bf%d0%be%d0%bf%d1%8b%d1%82%d0%ba%d0%b5-%d0%bf%d0%be%d0%bb%d1%83%d1%87%d0%b8%d1%82%d1%8c-%d1%81%d0%b2%d0%b5%d0%b4%d0%b5%d0%bd%d0%b8%d1%8f-%d0%be-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d0%b5

**Comment by VadimSam** [comment]
<potok matershiny> eta <roskomnadzor> rabotaet. Kak? <ROSCOMNADZOR>

**Comment by IvanTitan0ff** [comment]
What's wrong?
