### ISSUE TITLE
Platform independent std::system 

### ISSUE THREAD

**Issue by VadimSam** [VadimSam/LR3_Git#3]
Fix "std::system" calls to clear screen  to add cross platform support of program for UNIX and Windows.

**Comment by IvanTitan0ff** [comment]
So, I was looking for ways to do this task from yesterday, but no one was found. I think I should concentrate on 1st issue.

**Comment by VadimSam** [comment]
No, please deal with this issue first,  because it is much more easy than #1.

**Comment by IvanTitan0ff** [comment]
But I don't know how

**Comment by VadimSam** [comment]
Do some research. It's obvious, ya know.

**Comment by IvanTitan0ff** [comment]
Most searching results tell me about Qt. Do you know smth about it?

**Comment by VadimSam** [comment]
Ofc. It's one of the most popular GUI frameworks for C++, C#, Python, JS and Rust.

**Comment by IvanTitan0ff** [comment]
Can is help us?

**Comment by VadimSam** [comment]
Not now. Try to use another query.

**Comment by VadimSam** [comment]
Found anything? And what exactly your query is?

**Comment by IvanTitan0ff** [comment]
I've no idea about alternative

**Comment by VadimSam** [comment]
What exactly your query is?

**Comment by VadimSam** [comment]
Less than an hour...

**Comment by IvanTitan0ff** [comment]
You don't know the way of crossplatform suuport too, yes?

**Comment by VadimSam** [comment]
It's **YOUR** task to implement this feature. I am asking **YOU**, not myself.

**Comment by VadimSam** [comment]
Michele wants cooperative work. But as far as I can see, only my commits are significant. So, do your job, by yourself.

**Comment by VadimSam** [comment]
@IvanTitan0ff, updates?

**Comment by IvanTitan0ff** [comment]
maybe i should use "if" to rwecognise type of OS

**Comment by VadimSam** [comment]
How exactly?

**Comment by IvanTitan0ff** [comment]
i'm trying to find

**Comment by VadimSam** [comment]
Due to finding solution by myself I forced to lock conversation.

**Comment by IvanTitan0ff** [comment]
I've almost found

**Comment by VadimSam** [comment]
No need.
